apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophprofile.fullname" . }}-secrets
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-uri: {{ .Values.secrets.databaseUri | quote }}
  s3-access-key: {{ .Values.secrets.s3AccessKey | quote }}
  s3-secret-key: {{ .Values.secrets.s3SecretKey | quote }}
  rabbitmq-uri: {{ .Values.secrets.rabbitmqUri | quote }}
