{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gophprofile.serviceAccountName" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
---
{{- if and .Values.rbac.create .Values.podSecurityPolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gophprofile.fullname" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
rules:
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  resourceNames: [{{ include "gophprofile.fullname" . | quote }}]
  verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gophprofile.fullname" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gophprofile.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "gophprofile.serviceAccountName" . }}
{{- end }}
